package com.cybozu.labs.langdetect.util;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.MissingResourceException;
import java.util.ResourceBundle;

/**
 * This is {@link Messages} class generated by Eclipse automatically.
 * Users don't use this class directly.
 *
 * @author Nakatani Shuyo
 * @author Konstantin Gusarov
 */
final class Messages {
    private static final Logger LOGGER = LoggerFactory.getLogger(Messages.class);

    private static final String BUNDLE_NAME = "com.cybozu.labs.langdetect.util.messages"; //$NON-NLS-1$
    private static final ResourceBundle RESOURCE_BUNDLE = ResourceBundle.getBundle(BUNDLE_NAME);

    private Messages() {
    }

    static String getString(final String key) {
        try {
            return RESOURCE_BUNDLE.getString(key);
        } catch (final MissingResourceException e) {
            LOGGER.warn("Unable to find message for key " + key, e);
            return '!' + key + '!';
        }
    }
}
